"""Added a table for academic requests

Revision ID: 05511104c2ac
Revises: a1beaae127a3
Create Date: 2025-03-18 12:29:43.947807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05511104c2ac'
down_revision = 'a1beaae127a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_requests')
    # ### end Alembic commands ###
