"""Changed data type from string to JSON

Revision ID: 9e59330794c2
Revises: 05511104c2ac
Create Date: 2025-03-18 14:01:35.746060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e59330794c2'
down_revision = '05511104c2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_requests', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
